namespace RnwTileGenerator.App;

/// <summary>Texts of the self-update (update bar, download, update mode, start after an update). See UpdateTexts.cs.</summary>
internal static partial class LocalizationStrings
{
    private static void RegisterUpdates()
    {
        // -- update bar -------------------------------------------------------
        Loc.Add("update.bar.available", "New version {0} available (installed: {1}).", "Neue Version {0} verfügbar (installiert: {1}).", "Nueva versión {0} disponible (instalada: {1}).", "Nouvelle version {0} disponible (installée : {1}).", "Nuova versione {0} disponibile (installata: {1}).", "Доступна новая версия {0} (установлена: {1}).", "有新版本 {0} 可用（已安装：{1}）。");
        Loc.Add("update.bar.updated", "RNW Tile Generator was updated to version {0}.", "RNW Tile Generator wurde auf Version {0} aktualisiert.", "RNW Tile Generator se actualizó a la versión {0}.", "RNW Tile Generator a été mis à jour vers la version {0}.", "RNW Tile Generator è stato aggiornato alla versione {0}.", "RNW Tile Generator обновлён до версии {0}.", "RNW Tile Generator 已更新到版本 {0}。");
        Loc.Add("update.bar.install", "Update now", "Jetzt aktualisieren", "Actualizar ahora", "Mettre à jour", "Aggiorna ora", "Обновить сейчас", "立即更新");
        Loc.Add("update.bar.install.tip", "Download the new version, check it and restart RNW Tile Generator with it", "Neue Version herunterladen, prüfen und RNW Tile Generator damit neu starten", "Descargar la nueva versión, comprobarla y reiniciar RNW Tile Generator con ella", "Télécharger la nouvelle version, la vérifier et redémarrer RNW Tile Generator avec elle", "Scarica la nuova versione, verificala e riavvia RNW Tile Generator con essa", "Скачать новую версию, проверить её и перезапустить RNW Tile Generator", "下载新版本，校验后用它重新启动 RNW Tile Generator");
        Loc.Add("update.bar.releasePage", "Release page", "Release-Seite", "Página de la versión", "Page de la version", "Pagina della versione", "Страница релиза", "发布页面");
        Loc.Add("update.bar.releasePage.tip", "Opens the release page in the browser", "Öffnet die Release-Seite im Browser", "Abre la página de la versión en el navegador", "Ouvre la page de la version dans le navigateur", "Apre la pagina della versione nel browser", "Открывает страницу релиза в браузере", "在浏览器中打开发布页面");
        Loc.Add("update.bar.skip", "Skip this version", "Diese Version überspringen", "Omitir esta versión", "Ignorer cette version", "Salta questa versione", "Пропустить эту версию", "跳过此版本");
        Loc.Add("update.bar.later.tip", "Remind me later", "Später erinnern", "Recordármelo más tarde", "Me le rappeler plus tard", "Ricordamelo più tardi", "Напомнить позже", "稍后提醒我");

        // -- check ------------------------------------------------------------
        Loc.Add("update.check.title", "Check for updates", "Nach Updates suchen", "Buscar actualizaciones", "Rechercher des mises à jour", "Cerca aggiornamenti", "Проверить обновления", "检查更新");
        Loc.Add("update.available.title", "Update available", "Update verfügbar", "Actualización disponible", "Mise à jour disponible", "Aggiornamento disponibile", "Доступно обновление", "有可用更新");
        Loc.Add("update.available.question", "Version {0} is available (installed: {1}).\n\nYes: update now and restart\nNo: open the release page in the browser\nCancel: do nothing", "Version {0} ist verfügbar (installiert: {1}).\n\nJa: jetzt aktualisieren und neu starten\nNein: Release-Seite im Browser öffnen\nAbbrechen: nichts tun", "La versión {0} está disponible (instalada: {1}).\n\nSí: actualizar ahora y reiniciar\nNo: abrir la página de la versión en el navegador\nCancelar: no hacer nada", "La version {0} est disponible (installée : {1}).\n\nOui : mettre à jour maintenant et redémarrer\nNon : ouvrir la page de la version dans le navigateur\nAnnuler : ne rien faire", "La versione {0} è disponibile (installata: {1}).\n\nSì: aggiorna ora e riavvia\nNo: apri la pagina della versione nel browser\nAnnulla: non fare nulla", "Доступна версия {0} (установлена: {1}).\n\nДа: обновить сейчас и перезапустить\nНет: открыть страницу релиза в браузере\nОтмена: ничего не делать", "版本 {0} 可用（已安装：{1}）。\n\n是：立即更新并重新启动\n否：在浏览器中打开发布页面\n取消：不执行任何操作");
        Loc.Add("update.check.upToDate", "You are using the latest version ({0}).", "Du verwendest die neueste Version ({0}).", "Estás usando la versión más reciente ({0}).", "Vous utilisez la dernière version ({0}).", "Stai usando la versione più recente ({0}).", "У вас последняя версия ({0}).", "你正在使用最新版本（{0}）。");
        Loc.Add("update.check.noRelease", "No published version was found yet.", "Es wurde noch keine veröffentlichte Version gefunden.", "Todavía no se ha encontrado ninguna versión publicada.", "Aucune version publiée n'a encore été trouvée.", "Non è ancora stata trovata alcuna versione pubblicata.", "Опубликованная версия пока не найдена.", "尚未找到已发布的版本。");
        Loc.Add("update.check.failed", "The check failed: {0}", "Die Prüfung ist fehlgeschlagen: {0}", "La comprobación ha fallado: {0}", "La vérification a échoué : {0}", "Il controllo non è riuscito: {0}", "Проверка не удалась: {0}", "检查失败：{0}");

        // -- download ---------------------------------------------------------
        Loc.Add("update.download.title", "Downloading update", "Update wird heruntergeladen", "Descargando la actualización", "Téléchargement de la mise à jour", "Download dell'aggiornamento", "Загрузка обновления", "正在下载更新");
        Loc.Add("update.download.hint", "RNW Tile Generator downloads the new version from GitHub and checks its signature.", "RNW Tile Generator lädt die neue Version von GitHub und prüft ihre Signatur.", "RNW Tile Generator descarga la nueva versión desde GitHub y comprueba su firma.", "RNW Tile Generator télécharge la nouvelle version depuis GitHub et vérifie sa signature.", "RNW Tile Generator scarica la nuova versione da GitHub e ne verifica la firma.", "RNW Tile Generator загружает новую версию с GitHub и проверяет её подпись.", "RNW Tile Generator 正在从 GitHub 下载新版本并校验其签名。");
        Loc.Add("update.download.status", "Version {0}", "Version {0}", "Versión {0}", "Version {0}", "Versione {0}", "Версия {0}", "版本 {0}");
        Loc.Add("update.download.count", "{0}: {1} of {2} MB", "{0}: {1} von {2} MB", "{0}: {1} de {2} MB", "{0} : {1} sur {2} Mo", "{0}: {1} di {2} MB", "{0}: {1} из {2} МБ", "{0}：{1} / {2} MB");
        Loc.Add("update.cancel", "Cancel", "Abbrechen", "Cancelar", "Annuler", "Annulla", "Отмена", "取消");

        // -- update not possible ----------------------------------------------
        Loc.Add("update.notPossible.title", "Update not possible", "Update nicht möglich", "Actualización no posible", "Mise à jour impossible", "Aggiornamento non possibile", "Обновление невозможно", "无法更新");
        Loc.Add("update.notPossible.offer", "{0}\n\nOpen the release page in the browser and install the new version by hand?", "{0}\n\nRelease-Seite im Browser öffnen und die neue Version von Hand installieren?", "{0}\n\n¿Abrir la página de la versión en el navegador e instalar la nueva versión manualmente?", "{0}\n\nOuvrir la page de la version dans le navigateur et installer la nouvelle version à la main ?", "{0}\n\nAprire la pagina della versione nel browser e installare la nuova versione a mano?", "{0}\n\nОткрыть страницу релиза в браузере и установить новую версию вручную?", "{0}\n\n是否在浏览器中打开发布页面并手动安装新版本？");
        Loc.Add("update.notPossible.noInstallList", "This program folder does not come from an RNW Tile Generator release (the file list rnw-install-files.txt is missing). The self-update only works for released versions.", "Dieser Programmordner stammt nicht aus einem Release des RNW Tile Generator (die Dateiliste rnw-install-files.txt fehlt). Das Selbst-Update gibt es nur für veröffentlichte Versionen.", "Esta carpeta del programa no procede de una versión publicada de RNW Tile Generator (falta la lista de archivos rnw-install-files.txt). La actualización automática solo funciona con versiones publicadas.", "Ce dossier du programme ne provient pas d'une version publiée de RNW Tile Generator (la liste de fichiers rnw-install-files.txt manque). La mise à jour automatique ne fonctionne que pour les versions publiées.", "Questa cartella del programma non proviene da una versione pubblicata di RNW Tile Generator (manca l'elenco file rnw-install-files.txt). L'aggiornamento automatico funziona solo per le versioni pubblicate.", "Эта папка программы не из релиза RNW Tile Generator (нет списка файлов rnw-install-files.txt). Самообновление работает только для опубликованных версий.", "此程序文件夹并非来自 RNW Tile Generator 的发布版本（缺少文件列表 rnw-install-files.txt）。自动更新仅适用于已发布的版本。");
        Loc.Add("update.notPossible.protectedFolder", "RNW Tile Generator is in a protected folder ({0}). The self-update never runs with administrator rights. Move the program folder into your user profile, for example %LocalAppData%\\Programs\\RNW Tile Generator, and it will update itself from then on.", "RNW Tile Generator liegt in einem geschützten Ordner ({0}). Das Selbst-Update läuft bewusst nie mit Administratorrechten. Lege den Programmordner in dein Benutzerprofil, z. B. %LocalAppData%\\Programs\\RNW Tile Generator, dann aktualisiert er sich künftig selbst.", "RNW Tile Generator está en una carpeta protegida ({0}). La actualización automática nunca se ejecuta con derechos de administrador. Mueve la carpeta del programa a tu perfil de usuario, por ejemplo %LocalAppData%\\Programs\\RNW Tile Generator, y a partir de entonces se actualizará solo.", "RNW Tile Generator se trouve dans un dossier protégé ({0}). La mise à jour automatique ne s'exécute jamais avec des droits d'administrateur. Déplacez le dossier du programme dans votre profil utilisateur, par exemple %LocalAppData%\\Programs\\RNW Tile Generator, et il se mettra ensuite à jour tout seul.", "RNW Tile Generator si trova in una cartella protetta ({0}). L'aggiornamento automatico non viene mai eseguito con diritti di amministratore. Sposta la cartella del programma nel tuo profilo utente, ad esempio %LocalAppData%\\Programs\\RNW Tile Generator, e da allora si aggiornerà da solo.", "RNW Tile Generator находится в защищённой папке ({0}). Самообновление никогда не запускается с правами администратора. Переместите папку программы в свой профиль, например %LocalAppData%\\Programs\\RNW Tile Generator, и дальше она будет обновляться сама.", "RNW Tile Generator 位于受保护的文件夹（{0}）中。自动更新从不以管理员权限运行。请将程序文件夹移到你的用户目录中，例如 %LocalAppData%\\Programs\\RNW Tile Generator，之后它就会自动更新。");
        Loc.Add("update.alreadyRunning", "An update is already running for this program folder. Wait until it has finished.", "Für diesen Programmordner läuft gerade schon ein Update. Warte, bis es fertig ist.", "Ya se está ejecutando una actualización para esta carpeta del programa. Espera a que termine.", "Une mise à jour est déjà en cours pour ce dossier du programme. Attendez qu'elle soit terminée.", "È già in corso un aggiornamento per questa cartella del programma. Attendi che sia terminato.", "Для этой папки программы уже выполняется обновление. Дождитесь его завершения.", "此程序文件夹已有更新正在运行，请等待其完成。");
        Loc.Add("update.launchFailed", "The update mode could not be started: {0}\n\nLog: {1}", "Der Update-Modus konnte nicht gestartet werden: {0}\n\nProtokoll: {1}", "No se pudo iniciar el modo de actualización: {0}\n\nRegistro: {1}", "Le mode de mise à jour n'a pas pu démarrer : {0}\n\nJournal : {1}", "Impossibile avviare la modalità di aggiornamento: {0}\n\nRegistro: {1}", "Не удалось запустить режим обновления: {0}\n\nЖурнал: {1}", "无法启动更新模式：{0}\n\n日志：{1}");

        // -- package problems ---------------------------------------------------
        Loc.Add("update.problem.noSignedPackage", "This release contains no signed update package.", "Dieses Release enthält kein signiertes Update-Paket.", "Esta versión no contiene ningún paquete de actualización firmado.", "Cette version ne contient aucun paquet de mise à jour signé.", "Questa versione non contiene alcun pacchetto di aggiornamento firmato.", "Этот релиз не содержит подписанного пакета обновления.", "此版本不包含已签名的更新包。");
        Loc.Add("update.problem.badSignature", "The signature of the update package is invalid. The package may not come from the developer.", "Die Signatur des Update-Pakets ist ungültig. Das Paket stammt womöglich nicht vom Entwickler.", "La firma del paquete de actualización no es válida. Es posible que el paquete no provenga del desarrollador.", "La signature du paquet de mise à jour n'est pas valide. Le paquet ne provient peut-être pas du développeur.", "La firma del pacchetto di aggiornamento non è valida. Il pacchetto potrebbe non provenire dallo sviluppatore.", "Подпись пакета обновления недействительна. Возможно, пакет не от разработчика.", "更新包的签名无效，该更新包可能并非来自开发者。");
        Loc.Add("update.problem.invalidManifest", "The package description of the release cannot be read.", "Die Paketbeschreibung des Releases ist unlesbar.", "No se puede leer la descripción del paquete de la versión.", "La description du paquet de la version est illisible.", "La descrizione del pacchetto della versione non è leggibile.", "Описание пакета релиза не читается.", "无法读取此版本的更新包描述。");
        Loc.Add("update.problem.versionMismatch", "The version in the package does not match the release.", "Die Version im Paket passt nicht zum Release.", "La versión del paquete no coincide con la versión publicada.", "La version du paquet ne correspond pas à la version publiée.", "La versione nel pacchetto non corrisponde alla versione pubblicata.", "Версия в пакете не совпадает с релизом.", "更新包中的版本与发布版本不一致。");
        Loc.Add("update.problem.notNewer", "The package is not newer than the installed version.", "Das Paket ist nicht neuer als die installierte Version.", "El paquete no es más reciente que la versión instalada.", "Le paquet n'est pas plus récent que la version installée.", "Il pacchetto non è più recente della versione installata.", "Пакет не новее установленной версии.", "该更新包并不比已安装的版本新。");
        Loc.Add("update.problem.protocolTooNew", "This version can only be installed by hand.", "Diese Version kann nur von Hand installiert werden.", "Esta versión solo se puede instalar manualmente.", "Cette version ne peut être installée qu'à la main.", "Questa versione può essere installata solo a mano.", "Эту версию можно установить только вручную.", "此版本只能手动安装。");
        Loc.Add("update.problem.assetMissing", "The update package is missing from the release.", "Das Update-Paket fehlt im Release.", "Falta el paquete de actualización en la versión.", "Le paquet de mise à jour manque dans la version.", "Nella versione manca il pacchetto di aggiornamento.", "В релизе нет пакета обновления.", "此版本中缺少更新包。");
        Loc.Add("update.problem.sizeMismatch", "The size of the downloaded package is wrong.", "Die Größe des heruntergeladenen Pakets stimmt nicht.", "El tamaño del paquete descargado no es correcto.", "La taille du paquet téléchargé est incorrecte.", "La dimensione del pacchetto scaricato non è corretta.", "Размер загруженного пакета неверен.", "下载的更新包大小不正确。");
        Loc.Add("update.problem.hashMismatch", "The checksum of the downloaded package is wrong.", "Die Prüfsumme des heruntergeladenen Pakets stimmt nicht.", "La suma de comprobación del paquete descargado no es correcta.", "La somme de contrôle du paquet téléchargé est incorrecte.", "Il checksum del pacchetto scaricato non è corretto.", "Контрольная сумма загруженного пакета неверна.", "下载的更新包校验和不正确。");
        Loc.Add("update.problem.extractFailed", "The package could not be extracted.", "Das Paket konnte nicht entpackt werden.", "No se pudo descomprimir el paquete.", "Le paquet n'a pas pu être décompressé.", "Impossibile estrarre il pacchetto.", "Не удалось распаковать пакет.", "无法解压更新包。");
        Loc.Add("update.problem.network", "Download failed: {0}", "Download fehlgeschlagen: {0}", "La descarga ha fallado: {0}", "Le téléchargement a échoué : {0}", "Download non riuscito: {0}", "Загрузка не удалась: {0}", "下载失败：{0}");

        // -- ready ------------------------------------------------------------
        Loc.Add("update.ready.title", "Update ready", "Update bereit", "Actualización lista", "Mise à jour prête", "Aggiornamento pronto", "Обновление готово", "更新已就绪");
        Loc.Add("update.ready.question", "Version {0} is ready. RNW Tile Generator will close and restart. Unsaved work is lost.", "Version {0} ist bereit. RNW Tile Generator wird geschlossen und neu gestartet. Nicht gespeicherte Arbeit geht verloren.", "La versión {0} está lista. RNW Tile Generator se cerrará y se reiniciará. El trabajo no guardado se perderá.", "La version {0} est prête. RNW Tile Generator va se fermer et redémarrer. Le travail non enregistré sera perdu.", "La versione {0} è pronta. RNW Tile Generator verrà chiuso e riavviato. Il lavoro non salvato andrà perso.", "Версия {0} готова. RNW Tile Generator закроется и перезапустится. Несохранённая работа будет потеряна.", "版本 {0} 已就绪。RNW Tile Generator 将关闭并重新启动，未保存的工作将会丢失。");

        Loc.Add("update.ready.save", "Save project and restart", "Projekt speichern und neu starten", "Guardar proyecto y reiniciar", "Enregistrer le projet et redémarrer", "Salva il progetto e riavvia", "Сохранить проект и перезапустить", "保存项目并重新启动");
        Loc.Add("update.ready.restartNoSave", "Restart without saving", "Ohne Speichern neu starten", "Reiniciar sin guardar", "Redémarrer sans enregistrer", "Riavvia senza salvare", "Перезапустить без сохранения", "不保存直接重新启动");
        Loc.Add("update.ready.restart", "Restart", "Neu starten", "Reiniciar", "Redémarrer", "Riavvia", "Перезапустить", "重新启动");

        // -- Help menu --------------------------------------------------------
        Loc.Add("help.menu", "_Help", "_Hilfe", "A_yuda", "_Aide", "_Guida", "_Справка", "帮助(_H)");
        Loc.Add("help.checkUpdates", "Check for updates", "Nach Updates suchen", "Buscar actualizaciones", "Rechercher des mises à jour", "Cerca aggiornamenti", "Проверить обновления", "检查更新");
        Loc.Add("help.checkUpdates.tip", "Looks on GitHub for a newer version", "Sucht auf GitHub nach einer neueren Version", "Busca en GitHub una versión más reciente", "Cherche une version plus récente sur GitHub", "Cerca su GitHub una versione più recente", "Ищет более новую версию на GitHub", "在 GitHub 上查找更新的版本");
        Loc.Add("help.checkAtStartup", "Check for updates at startup", "Beim Start nach Updates suchen", "Buscar actualizaciones al iniciar", "Rechercher des mises à jour au démarrage", "Cerca aggiornamenti all'avvio", "Проверять обновления при запуске", "启动时检查更新");
        Loc.Add("help.checkAtStartup.tip", "At most once a day. Only asks GitHub for the latest version number, sends no data about you or your tiles.", "Höchstens einmal am Tag. Fragt bei GitHub nur die neueste Versionsnummer ab und sendet keine Daten über dich oder deine Tiles.", "Como máximo una vez al día. Solo consulta a GitHub el número de la última versión y no envía datos sobre ti ni tus tiles.", "Au plus une fois par jour. Demande seulement à GitHub le numéro de la dernière version, n'envoie aucune donnée sur vous ou vos tuiles.", "Al massimo una volta al giorno. Chiede a GitHub solo il numero dell'ultima versione, non invia dati su di te o sui tuoi tile.", "Не чаще раза в день. Запрашивает у GitHub только номер последней версии, никаких данных о вас или ваших тайлах не отправляет.", "每天最多一次。只向 GitHub 查询最新版本号，不发送任何关于你或你的地块的数据。");
        Loc.Add("help.reportBug", "Report a bug", "Fehler melden", "Informar de un error", "Signaler un bug", "Segnala un bug", "Сообщить об ошибке", "报告错误");
        Loc.Add("help.changelog", "Changelog", "Changelog", "Registro de cambios", "Journal des modifications", "Registro delle modifiche", "Список изменений", "更新日志");
        Loc.Add("help.changelog.missing", "Readme\\Changelog.txt is missing in the program folder.", "Readme\\Changelog.txt fehlt im Programmordner.", "Falta Readme\\Changelog.txt en la carpeta del programa.", "Readme\\Changelog.txt manque dans le dossier du programme.", "Readme\\Changelog.txt manca nella cartella del programma.", "В папке программы нет Readme\\Changelog.txt.", "程序文件夹中缺少 Readme\\Changelog.txt。");
        Loc.Add("help.about", "About", "Über", "Acerca de", "À propos", "Informazioni", "О программе", "关于");
        Loc.Add("help.about.title", "About RNW Tile Generator", "Über RNW Tile Generator", "Acerca de RNW Tile Generator", "À propos de RNW Tile Generator", "Informazioni su RNW Tile Generator", "О программе RNW Tile Generator", "关于 RNW Tile Generator");
        Loc.Add("help.about.version", "Version {0}", "Version {0}", "Versión {0}", "Version {0}", "Versione {0}", "Версия {0}", "版本 {0}");
        Loc.Add("help.about.license", "Free software under the MIT license.", "Freie Software unter der MIT-Lizenz.", "Software libre bajo la licencia MIT.", "Logiciel libre sous licence MIT.", "Software libero con licenza MIT.", "Свободное ПО под лицензией MIT.", "基于 MIT 许可证的自由软件。");
        Loc.Add("help.about.repository", "Source code, releases and bug reports:", "Quellcode, Releases und Fehlerberichte:", "Código fuente, versiones e informes de errores:", "Code source, versions et rapports de bugs :", "Codice sorgente, versioni e segnalazioni di bug:", "Исходный код, релизы и сообщения об ошибках:", "源代码、发布版本和错误报告：");
        Loc.Add("help.about.close", "Close", "Schließen", "Cerrar", "Fermer", "Chiudi", "Закрыть", "关闭");

        // -- update mode ------------------------------------------------------
        Loc.Add("update.apply.title", "Updating RNW Tile Generator", "RNW Tile Generator wird aktualisiert", "Actualizando RNW Tile Generator", "Mise à jour de RNW Tile Generator", "Aggiornamento di RNW Tile Generator", "Обновление RNW Tile Generator", "正在更新 RNW Tile Generator");
        Loc.Add("update.apply.versions", "Version {0} is replaced by {1}.", "Version {0} wird durch {1} ersetzt.", "La versión {0} se sustituye por {1}.", "La version {0} est remplacée par {1}.", "La versione {0} viene sostituita da {1}.", "Версия {0} заменяется на {1}.", "版本 {0} 将被 {1} 替换。");
        Loc.Add("update.apply.phase.waiting", "Waiting for {0} open RNW Tile Generator windows. Please close them.", "Warte auf {0} offene Fenster des RNW Tile Generator. Bitte schließen.", "Esperando a {0} ventanas abiertas de RNW Tile Generator. Ciérralas, por favor.", "En attente de {0} fenêtres ouvertes de RNW Tile Generator. Veuillez les fermer.", "In attesa di {0} finestre aperte di RNW Tile Generator. Chiudile, per favore.", "Ожидание {0} открытых окон RNW Tile Generator. Закройте их.", "正在等待 {0} 个打开的 RNW Tile Generator 窗口，请关闭它们。");
        Loc.Add("update.apply.phase.swapping", "Replacing files", "Dateien werden ersetzt", "Sustituyendo archivos", "Remplacement des fichiers", "Sostituzione dei file", "Замена файлов", "正在替换文件");
        Loc.Add("update.apply.phase.starting", "Starting the new version", "Neue Version wird gestartet", "Iniciando la nueva versión", "Démarrage de la nouvelle version", "Avvio della nuova versione", "Запуск новой версии", "正在启动新版本");
        Loc.Add("update.apply.phase.checking", "Waiting for the new version to start", "Warte auf den Start der neuen Version", "Esperando a que se inicie la nueva versión", "En attente du démarrage de la nouvelle version", "In attesa dell'avvio della nuova versione", "Ожидание запуска новой версии", "正在等待新版本启动");
        Loc.Add("update.apply.phase.rollingBack", "Update failed, restoring the old version", "Update fehlgeschlagen, alte Version wird wiederhergestellt", "La actualización ha fallado, restaurando la versión anterior", "La mise à jour a échoué, restauration de l'ancienne version", "Aggiornamento non riuscito, ripristino della versione precedente", "Обновление не удалось, восстановление старой версии", "更新失败，正在恢复旧版本");
        Loc.Add("update.apply.keepWaiting.title", "Windows still open", "Noch offene Fenster", "Ventanas aún abiertas", "Fenêtres encore ouvertes", "Finestre ancora aperte", "Окна ещё открыты", "仍有窗口打开");
        Loc.Add("update.apply.keepWaiting", "{0} RNW Tile Generator windows are still open. The update waits until all of them are closed.\n\nKeep waiting?", "Es sind noch {0} Fenster des RNW Tile Generator offen. Das Update wartet, bis alle geschlossen sind.\n\nWeiter warten?", "Todavía hay {0} ventanas de RNW Tile Generator abiertas. La actualización espera hasta que se cierren todas.\n\n¿Seguir esperando?", "{0} fenêtres de RNW Tile Generator sont encore ouvertes. La mise à jour attend qu'elles soient toutes fermées.\n\nContinuer à attendre ?", "Ci sono ancora {0} finestre di RNW Tile Generator aperte. L'aggiornamento attende che vengano chiuse tutte.\n\nContinuare ad attendere?", "Ещё открыто окон RNW Tile Generator: {0}. Обновление ждёт, пока все они не будут закрыты.\n\nПродолжать ждать?", "仍有 {0} 个 RNW Tile Generator 窗口打开。更新将等待所有窗口关闭。\n\n继续等待？");
        Loc.Add("update.apply.rollbackFailed", "The old version could not be restored.\n\nIt is complete in the folder {0}. Copy its content back into the program folder by hand.\n\nLog: {1}", "Die alte Version konnte nicht wiederhergestellt werden.\n\nSie liegt vollständig im Ordner {0}. Kopiere ihren Inhalt von Hand zurück in den Programmordner.\n\nProtokoll: {1}", "No se pudo restaurar la versión anterior.\n\nEstá completa en la carpeta {0}. Copia su contenido manualmente de vuelta a la carpeta del programa.\n\nRegistro: {1}", "L'ancienne version n'a pas pu être restaurée.\n\nElle se trouve complète dans le dossier {0}. Recopiez son contenu à la main dans le dossier du programme.\n\nJournal : {1}", "Impossibile ripristinare la versione precedente.\n\nSi trova completa nella cartella {0}. Copiane a mano il contenuto nella cartella del programma.\n\nRegistro: {1}", "Не удалось восстановить старую версию.\n\nОна полностью находится в папке {0}. Скопируйте её содержимое вручную обратно в папку программы.\n\nЖурнал: {1}", "无法恢复旧版本。\n\n旧版本完整保存在文件夹 {0} 中，请手动将其内容复制回程序文件夹。\n\n日志：{1}");
        Loc.Add("update.apply.invalidArguments", "Invalid call of the update mode.", "Ungültiger Aufruf des Update-Modus.", "Llamada no válida del modo de actualización.", "Appel non valide du mode de mise à jour.", "Chiamata non valida della modalità di aggiornamento.", "Недопустимый вызов режима обновления.", "更新模式的调用无效。");

        // -- start after an update --------------------------------------------
        Loc.Add("update.start.failed.title", "Update failed", "Update fehlgeschlagen", "La actualización ha fallado", "Échec de la mise à jour", "Aggiornamento non riuscito", "Обновление не удалось", "更新失败");
        Loc.Add("update.start.failed", "The update to version {0} failed. The old version was restored.\n\nDetails in the log: {1}", "Das Update auf Version {0} ist fehlgeschlagen. Die alte Version wurde wiederhergestellt.\n\nDetails im Protokoll: {1}", "La actualización a la versión {0} ha fallado. Se ha restaurado la versión anterior.\n\nDetalles en el registro: {1}", "La mise à jour vers la version {0} a échoué. L'ancienne version a été restaurée.\n\nDétails dans le journal : {1}", "L'aggiornamento alla versione {0} non è riuscito. È stata ripristinata la versione precedente.\n\nDettagli nel registro: {1}", "Обновление до версии {0} не удалось. Старая версия восстановлена.\n\nПодробности в журнале: {1}", "更新到版本 {0} 失败，已恢复旧版本。\n\n详情见日志：{1}");
        Loc.Add("update.start.cancelled.title", "Update cancelled", "Update abgebrochen", "Actualización cancelada", "Mise à jour annulée", "Aggiornamento annullato", "Обновление отменено", "更新已取消");
        Loc.Add("update.start.cancelled", "The update to version {0} was cancelled. Nothing was changed.", "Das Update auf Version {0} wurde abgebrochen. Es wurde nichts verändert.", "La actualización a la versión {0} se ha cancelado. No se ha cambiado nada.", "La mise à jour vers la version {0} a été annulée. Rien n'a été modifié.", "L'aggiornamento alla versione {0} è stato annullato. Non è stato modificato nulla.", "Обновление до версии {0} отменено. Ничего не изменено.", "更新到版本 {0} 已取消，未做任何更改。");

        // -- browser ----------------------------------------------------------
        Loc.Add("update.browser.notOpened.title", "Not opened", "Nicht geöffnet", "No abierto", "Non ouvert", "Non aperto", "Не открыто", "未打开");
        Loc.Add("update.browser.notGitHub", "The release address does not point to GitHub and is therefore not opened.", "Die Release-Adresse verweist nicht auf GitHub und wird deshalb nicht geöffnet.", "La dirección de la versión no apunta a GitHub y por eso no se abre.", "L'adresse de la version ne pointe pas vers GitHub et n'est donc pas ouverte.", "L'indirizzo della versione non punta a GitHub e quindi non viene aperto.", "Адрес релиза не ведёт на GitHub, поэтому он не открывается.", "发布地址未指向 GitHub，因此不会打开。");
        Loc.Add("update.browser.error.title", "Error", "Fehler", "Error", "Erreur", "Errore", "Ошибка", "错误");
        Loc.Add("update.browser.failed", "The browser could not be opened: {0}", "Der Browser konnte nicht geöffnet werden: {0}", "No se pudo abrir el navegador: {0}", "Le navigateur n'a pas pu être ouvert : {0}", "Impossibile aprire il browser: {0}", "Не удалось открыть браузер: {0}", "无法打开浏览器：{0}");
    }
}
