namespace RnwTileGenerator.App;

/// <summary>Texts of the bug report window (BugReportWindow.cs) and of the crash dialog (CrashHandling.cs).</summary>
internal static partial class LocalizationStrings
{
    private static void RegisterBugs()
    {
        // -- bug report window --------------------------------------------------
        Loc.Add("bug.title", "Report a bug", "Fehler melden", "Informar de un error", "Signaler un bug", "Segnala un bug", "Сообщить об ошибке", "报告错误");
        Loc.Add("bug.intro", "Describe what went wrong. You see the complete report below before you send it; nothing is sent automatically.", "Beschreibe, was schiefgelaufen ist. Unten siehst du den ganzen Bericht, bevor du ihn abschickst; nichts wird automatisch gesendet.", "Describe qué ha fallado. Abajo ves el informe completo antes de enviarlo; no se envía nada automáticamente.", "Décrivez ce qui n'a pas fonctionné. Vous voyez le rapport complet ci-dessous avant de l'envoyer ; rien n'est envoyé automatiquement.", "Descrivi cosa è andato storto. Sotto vedi il rapporto completo prima di inviarlo; non viene inviato nulla automaticamente.", "Опишите, что пошло не так. Ниже вы видите весь отчёт до отправки; ничего не отправляется автоматически.", "请描述出了什么问题。发送前你可以在下方看到完整的报告；不会自动发送任何内容。");
        Loc.Add("bug.field.title", "Title (short summary)", "Titel (kurze Zusammenfassung)", "Título (resumen breve)", "Titre (bref résumé)", "Titolo (breve riepilogo)", "Заголовок (кратко)", "标题（简要概述）");
        Loc.Add("bug.field.what", "What happened?", "Was ist passiert?", "¿Qué ha pasado?", "Que s'est-il passé ?", "Cosa è successo?", "Что произошло?", "发生了什么？");
        Loc.Add("bug.field.steps", "Steps to reproduce", "Schritte zum Nachstellen", "Pasos para reproducirlo", "Étapes pour reproduire", "Passaggi per riprodurlo", "Шаги для воспроизведения", "重现步骤");
        Loc.Add("bug.field.expected", "Expected / actual", "Erwartet / tatsächlich", "Esperado / real", "Attendu / obtenu", "Atteso / effettivo", "Ожидалось / на самом деле", "预期 / 实际");
        Loc.Add("bug.includeLog", "Include crash log (last entries, personal paths removed)", "Absturzprotokoll anhängen (letzte Einträge, persönliche Pfade entfernt)", "Incluir el registro de fallos (últimas entradas, rutas personales eliminadas)", "Joindre le journal de plantage (dernières entrées, chemins personnels supprimés)", "Includi il registro degli arresti anomali (ultime voci, percorsi personali rimossi)", "Приложить журнал сбоев (последние записи, личные пути удалены)", "附上崩溃日志（最近的条目，已移除个人路径）");
        Loc.Add("bug.preview", "Report preview (English, as it will be sent)", "Vorschau des Berichts (Englisch, so wie er gesendet wird)", "Vista previa del informe (en inglés, tal como se enviará)", "Aperçu du rapport (en anglais, tel qu'il sera envoyé)", "Anteprima del rapporto (in inglese, così come verrà inviato)", "Предпросмотр отчёта (на английском, в том виде, в каком он будет отправлен)", "报告预览（英文，即将发送的内容）");
        Loc.Add("bug.attachHint", "Files (project, tile, screenshot) cannot be attached automatically. On GitHub drag them into the issue; in an email attach them.", "Dateien (Projekt, Tile, Screenshot) lassen sich nicht automatisch anhängen. Auf GitHub ziehst du sie ins Issue, bei einer E-Mail hängst du sie an.", "Los archivos (proyecto, tile, captura) no se pueden adjuntar automáticamente. En GitHub arrástralos al issue; en un correo, adjúntalos.", "Les fichiers (projet, tuile, capture d'écran) ne peuvent pas être joints automatiquement. Sur GitHub, glissez-les dans l'issue ; dans un e-mail, joignez-les.", "I file (progetto, tile, screenshot) non si possono allegare automaticamente. Su GitHub trascinali nell'issue; in un'e-mail allegali.", "Файлы (проект, тайл, скриншот) нельзя приложить автоматически. На GitHub перетащите их в issue, в письме — приложите.", "文件（项目、地块、截图）无法自动附加。在 GitHub 上请将其拖入 issue；在邮件中请作为附件添加。");
        Loc.Add("bug.github", "Report on GitHub", "Auf GitHub melden", "Informar en GitHub", "Signaler sur GitHub", "Segnala su GitHub", "Сообщить на GitHub", "在 GitHub 上报告");
        Loc.Add("bug.github.tip", "Opens a prefilled issue in the browser. Needs a GitHub account.", "Öffnet ein vorbefülltes Issue im Browser. Dafür brauchst du ein GitHub-Konto.", "Abre un issue ya rellenado en el navegador. Necesitas una cuenta de GitHub.", "Ouvre une issue pré-remplie dans le navigateur. Nécessite un compte GitHub.", "Apre un'issue già compilata nel browser. Serve un account GitHub.", "Открывает заполненный issue в браузере. Нужна учётная запись GitHub.", "在浏览器中打开已预填的 issue。需要 GitHub 帐户。");
        Loc.Add("bug.email", "Send by email", "Per E-Mail senden", "Enviar por correo", "Envoyer par e-mail", "Invia per e-mail", "Отправить по e-mail", "通过电子邮件发送");
        Loc.Add("bug.email.tip", "Opens your mail program with a prefilled message.", "Öffnet dein Mailprogramm mit einer vorbefüllten Nachricht.", "Abre tu programa de correo con un mensaje ya rellenado.", "Ouvre votre logiciel de messagerie avec un message pré-rempli.", "Apre il tuo programma di posta con un messaggio già compilato.", "Открывает почтовую программу с заполненным письмом.", "用预填的邮件打开你的邮件程序。");
        Loc.Add("bug.copy", "Copy report", "Bericht kopieren", "Copiar informe", "Copier le rapport", "Copia rapporto", "Копировать отчёт", "复制报告");
        Loc.Add("bug.copied", "The report was copied to the clipboard.", "Der Bericht wurde in die Zwischenablage kopiert.", "El informe se ha copiado al portapapeles.", "Le rapport a été copié dans le presse-papiers.", "Il rapporto è stato copiato negli appunti.", "Отчёт скопирован в буфер обмена.", "报告已复制到剪贴板。");
        Loc.Add("bug.openFolder", "Open program folder", "Programmordner öffnen", "Abrir carpeta del programa", "Ouvrir le dossier du programme", "Apri cartella del programma", "Открыть папку программы", "打开程序文件夹");
        Loc.Add("bug.openFolder.tip", "crash_log.txt lies in this folder.", "Dort liegt crash_log.txt.", "Ahí está crash_log.txt.", "crash_log.txt se trouve dans ce dossier.", "Lì si trova crash_log.txt.", "Там находится crash_log.txt.", "crash_log.txt 位于该文件夹中。");
        Loc.Add("bug.close", "Close", "Schließen", "Cerrar", "Fermer", "Chiudi", "Закрыть", "关闭");
        Loc.Add("bug.titleRequired", "Enter a title first.", "Gib zuerst einen Titel ein.", "Escribe primero un título.", "Saisissez d'abord un titre.", "Inserisci prima un titolo.", "Сначала введите заголовок.", "请先输入标题。");
        Loc.Add("bug.truncated", "The report was too long and was shortened. The full text is in the clipboard; paste it in place of the shortened text.", "Der Bericht war zu lang und wurde gekürzt. Der vollständige Text liegt in der Zwischenablage; füge ihn an Stelle des gekürzten Texts ein.", "El informe era demasiado largo y se ha acortado. El texto completo está en el portapapeles; pégalo en lugar del texto acortado.", "Le rapport était trop long et a été raccourci. Le texte complet est dans le presse-papiers ; collez-le à la place du texte raccourci.", "Il rapporto era troppo lungo ed è stato accorciato. Il testo completo è negli appunti; incollalo al posto di quello accorciato.", "Отчёт был слишком длинным и сокращён. Полный текст в буфере обмена; вставьте его вместо сокращённого.", "报告过长，已被截短。完整文本已复制到剪贴板，请粘贴替换截短的文本。");
        Loc.Add("bug.noMailProgram", "No mail program could be opened. The report was copied to the clipboard; please send it to {0}.", "Es konnte kein Mailprogramm geöffnet werden. Der Bericht liegt in der Zwischenablage; bitte schick ihn an {0}.", "No se pudo abrir ningún programa de correo. El informe está en el portapapeles; envíalo a {0}.", "Aucun logiciel de messagerie n'a pu être ouvert. Le rapport est dans le presse-papiers ; envoyez-le à {0}.", "Non è stato possibile aprire alcun programma di posta. Il rapporto è negli appunti; invialo a {0}.", "Не удалось открыть почтовую программу. Отчёт в буфере обмена; отправьте его на {0}.", "无法打开任何邮件程序。报告已复制到剪贴板，请将其发送到 {0}。");

        // -- crash dialog -------------------------------------------------------
        Loc.Add("crash.title.continue", "An error occurred", "Ein Fehler ist aufgetreten", "Se ha producido un error", "Une erreur s'est produite", "Si è verificato un errore", "Произошла ошибка", "发生错误");
        Loc.Add("crash.title.fatal", "Unexpected error - the program will close", "Unerwarteter Fehler - Programm wird beendet", "Error inesperado: el programa se cerrará", "Erreur inattendue - le programme va se fermer", "Errore imprevisto - il programma verrà chiuso", "Непредвиденная ошибка — программа будет закрыта", "意外错误 - 程序将关闭");
        Loc.Add("crash.header.continue", "An error occurred. The program keeps running, but the last step may not have been applied.\nPlease report it with the button below, or copy the text (it is also saved in crash_log.txt next to the .exe).", "Es ist ein Fehler aufgetreten. Das Programm läuft weiter, aber der letzte Schritt ist eventuell nicht angewendet worden.\nBitte melde ihn mit dem Knopf unten oder kopiere den Text (auch gespeichert in crash_log.txt neben der .exe).", "Se ha producido un error. El programa sigue funcionando, pero es posible que el último paso no se haya aplicado.\nInfórmalo con el botón de abajo o copia el texto (también se guarda en crash_log.txt junto al .exe).", "Une erreur s'est produite. Le programme continue, mais la dernière étape n'a peut-être pas été appliquée.\nSignalez-la avec le bouton ci-dessous ou copiez le texte (également enregistré dans crash_log.txt à côté du .exe).", "Si è verificato un errore. Il programma continua a funzionare, ma l'ultimo passaggio potrebbe non essere stato applicato.\nSegnalalo con il pulsante qui sotto o copia il testo (salvato anche in crash_log.txt accanto al .exe).", "Произошла ошибка. Программа продолжает работать, но последний шаг мог не примениться.\nСообщите о ней кнопкой ниже или скопируйте текст (он также сохранён в crash_log.txt рядом с .exe).", "发生错误。程序会继续运行，但上一步可能未生效。\n请用下方按钮报告，或复制文本（也保存在 .exe 旁的 crash_log.txt 中）。");
        Loc.Add("crash.header.fatal", "A serious error occurred and the program has to close.\nPlease report it with the button below, or copy the text (it is also saved in crash_log.txt next to the .exe).", "Ein schwerwiegender Fehler ist aufgetreten und das Programm muss beendet werden.\nBitte melde ihn mit dem Knopf unten oder kopiere den Text (auch gespeichert in crash_log.txt neben der .exe).", "Se ha producido un error grave y el programa tiene que cerrarse.\nInfórmalo con el botón de abajo o copia el texto (también se guarda en crash_log.txt junto al .exe).", "Une erreur grave s'est produite et le programme doit se fermer.\nSignalez-la avec le bouton ci-dessous ou copiez le texte (également enregistré dans crash_log.txt à côté du .exe).", "Si è verificato un errore grave e il programma deve essere chiuso.\nSegnalalo con il pulsante qui sotto o copia il testo (salvato anche in crash_log.txt accanto al .exe).", "Произошла серьёзная ошибка, программа должна закрыться.\nСообщите о ней кнопкой ниже или скопируйте текст (он также сохранён в crash_log.txt рядом с .exe).", "发生严重错误，程序必须关闭。\n请用下方按钮报告，或复制文本（也保存在 .exe 旁的 crash_log.txt 中）。");
        Loc.Add("crash.copy", "Copy to clipboard", "In Zwischenablage kopieren", "Copiar al portapapeles", "Copier dans le presse-papiers", "Copia negli appunti", "Копировать в буфер обмена", "复制到剪贴板");
        Loc.Add("crash.report", "Report bug", "Fehler melden", "Informar del error", "Signaler le bug", "Segnala il bug", "Сообщить об ошибке", "报告错误");
        Loc.Add("crash.close", "Close", "Schließen", "Cerrar", "Fermer", "Chiudi", "Закрыть", "关闭");
        Loc.Add("crash.quit", "Quit program", "Programm beenden", "Salir del programa", "Quitter le programme", "Esci dal programma", "Закрыть программу", "退出程序");
    }
}
